---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: centos-6.6
  run_list:
  - recipe[yum]
- name: centos-7.1
  run_list:
  - recipe[yum]

suites:
- name: default
  run_list:
    - recipe[camo]
  attributes:
- name: runit
  excludes:
    - ubuntu-12.04
    - ubuntu-14.04
    - centos-7.1
  run_list:
    - recipe[camo]
  attributes:
    camo:
      init_style: runit
- name: package
  excludes:
    - ubuntu-12.04
    - centos-6.6
    - centos-7.1
  run_list:
    - recipe[camo]
  attributes:
    camo:
      install_method: package
