sudo: false
language: ruby
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/91b2d93dccdda9c43a4c
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
rvm:
  - 2.2.3
bundler_args: --without integration development
script:
  - bundle exec rake default
